export const EMAIL_CHANGED = 'EMAIL_CHANGED';

export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER = 'LOGIN_USER';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
