export const EMAIL_CHANGED = 'EMAIL_CHANGED';

export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER = 'LOGIN_USER';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const SIGNUP_USER = 'SIGNUP_USER';

export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';

export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const CHANGE_IF_LOGGING_IN_USER = 'CHANGE_IF_LOGGING_IN_USER';

export const CHANGE_IF_SIGNING_UP_USER = 'CHANGE_IF_SIGNING_UP_USER';

export const CLEAN_UP_LOGIN_ERROR_MESSAGE = 'CLEAN_UP_LOGIN_ERROR_MESSAGE';

export const CLEAN_UP_SIGNUP_ERROR_MESSAGE = 'CLEAN_UP_SIGNUP_ERROR_MESSAGE';
