export const FIREBASE_API_KEY = <YOUR_FIREBASE_API_KEY>;
export const FIREBASE_AUTH_DOMAIN = <YOUR_FIREBASE_AUTH_DOMAIN>;
export const FIREBASE_DATABASE_URL = <YOUR_FIREBASE_DATABASE_URL>;
export const FIREBASE_PROJECT_ID = <YOUR_FIREBASE_PROJECT_ID>;
export const FIREBASE_STORAGE_BUCKET = <YOUR_FIREBASE_STORAGE_BUCKET>;
export const FIREBASE_MESSAGING_SENDER_ID = <YOUR_FIREBASE_MESSAGING_SENDER_ID>;